### ISSUE TITLE
Region for Bucket needs to be defined

### ISSUE THREAD

**Issue by benburch** [elasticio/aws-s3-component#16]
Following changes to AWS documented here: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro 

**Buckets created in Regions launched after March 20, 2019 are not reachable via the https://bucket.s3.amazonaws.com naming scheme**

This BUG has been identified by a client in the US-East-1 region, this appears to have to call the API using a special case: "If your bucket is in the US East (N. Virginia) Region, you must use the http://s3.amazonaws.com/bucket endpoint."

I am unsure from the component if the URL we are calling is the "virtual-hosted–style URL" or the "path-style URL".

This needs to be investigated and determined if there is a fault or amendment needed in the component.

**Comment by benburch** [comment]
Customer fixed this:

> I cloned the S3 component and made some minor changes in our elastic.io team’s version to make this work.
Added “region” in the UI and in all the actions
Commented the listing of objects in a blank bucket during verification.  This was throwing an exception.  I do not have rights to list anything other than my assigned bucket.  Verification now works and I can list objects and write attachments.

Looking for PS to resolve and fix this in our component ASAP please.

**Comment by jhorbulyk** [comment]
Code change was made in https://github.com/elasticio/aws-s3-component/pull/17 but it needs to be tested and deployed.
