### ISSUE TITLE
Don't create attachments that are too big

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/aws-s3-component#21]
An error should be thrown before trying to create an attachment, if the attachment would exceed the maximum allowed attachment size. The maximum allowed attachment size should be read as an environment variable.

Before writing any files from S3 server to Steward, the size of the file should be checked. If it is above the threshold, an error should be emitted and no data transfered to Steward.

**Comment by stas-fomenko** [comment]
AWS-S3 Trigger tries to create attachments that are too big (unsuccessfully) again and does not throw an error.
Currently, trigger creates attachment of retrieved file incorrectly: created file size is smaller then the actual file size

**Comment by if0s** [comment]
Hi @jhorbulyk 
What max size should be used as default? Currently in `Read Files` action it set to `10 000 000` (almost 10MB), but for example in SFTP we use `104 857 600` (100MB)

**Comment by jhorbulyk** [comment]
> What max size should be used as default? Currently in `Read Files` action it set to `10 000 000` (almost 10MB), but for example in SFTP we use `104 857 600` (100MB)

Let's use `104 857 600` as the default.
