### ISSUE TITLE
Rename configuration fields in Lookup from table action

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/aws-s3-component#28]
**Description:**
Currently action `Lookup from table` has config fields with incorrect names, the should be renamed:
`From this table` -> `From this column`
`To this table` -> `To this column`

![image](https://user-images.githubusercontent.com/36419533/71244788-f9c8d880-231b-11ea-8608-a2d1747d482e.png)

Where to rename:

- component.json
- Readme.md

**Comment by kirill-levitskiy** [comment]
Moved https://github.com/elasticio/dictionary-component/issues/5
