### ISSUE TITLE
can't push master (570ff115cacb4af003a4a9c89739e301ace43969) to telekom

### ISSUE THREAD

**Issue by Nazar910** [elasticio/aws-s3-component#3]
![image](https://user-images.githubusercontent.com/19594637/45414180-800b5f00-b683-11e8-81ce-bc258c0eaa0d.png)

**Comment by kirill-levitskiy** [comment]
I've updated version of sailor module for the component in commit 
12c9b8fac85198a2be7d9771b5b2676e7df935e8
