### ISSUE TITLE
Invalid respose on non-deleted file in Delete file action

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/aws-s3-component#31]
Description: currently action returns input of `filename` field, according to [OIH Descriptions of standardized actions or triggers](https://github.com/elasticio/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#delete-object) it should return `{}` in a case when an object was not deleted: 

Preconditions: use creds from Bitwarden.

STR:
1. Create flow: step1 - simple trigger
2. step2 - AWS S3: Delete file action
input:
`Bucket Name and Folder`: `"lloyds-dev"` (valid input) 
`filename`: `"wefxwfcecf"` (invalid input)
3. Retrieve sample

AR: 
sample retrieved
output:
`{
  "filename": "wefxwfcecf"
}`

ER: `{}`

**Comment by ShkarupaNick** [comment]
I can suggest adding a new property `Throw an error if not exists` to the action and update it in the OIH standards. Also, check this requirement in the OIH library.

**Comment by jhorbulyk** [comment]
I'm not sure that there is a need to check or to have different behavior whether or not the file exists.  In my mind, a "delete file if it exists" behavior is fine.
