### ISSUE TITLE
Component doesn't work at the current version of platform

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/aws-s3-component#4]
The component can be successfully deployed to the eio-platform, but the current version of the eio-platform doesn't support `CSVWriteHeader` type of field in an input configuration.

component.json:
```
        "csv": {
          "viewClass": "CSVWriteHeader",
          "label": "CSV Header",
          "placeholder": "Copy and paste here first (header) line of your CSV file here",
          "required": true
        }
```

**Comment by khanzadyan** [comment]
Could it be replaced with the `CSVWriteView` class?

**Comment by kirill-levitskiy** [comment]
Thank you for the tip. I've made changes to the component in the commit f3d95d8e654b922a8fd8b033beb6757db3bd221e
