### ISSUE TITLE
Revitalize this component

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/aws-s3-component#6]
- [ ] Make sure that this component adheres to the common definition of done.  
- [x] Make sure that passwords in credentials are valid.  
- [x] Use the latest versions of dependencies.  
- [x] Mark actions that aren't sensible as depricated.  
- [x] Include relevant information in the Readme
- [x] Start component completeness matrix
- [x] Make sure S3 Credentials are in BitWarden

**Comment by zubairov** [comment]
@elasticio/ps credentials to access S3 bucket called `lloyds-dev` can be found in Bitwarden

**Comment by kirill-levitskiy-elasticio** [comment]
@zubairov could you check the access level to creds in Bitwarden, please? I can't see them right now.

**Comment by kirill-levitskiy** [comment]
In the checklist above almost all items have been checked. The only item is not possible to be checked is to comply the definition of done due to uncommon purpose of the component.

In my view, the issue can be closed.
