### ISSUE TITLE
Add an action: Upsert S3 Object (aka File) By Key (aka ID/Filename)

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/aws-s3-component#7]
[OIH Guideline](https://github.com/openintegrationhub/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#iteration-1-upsert-object-by-id)

## Config Fields
None Required

## Input Metadata
* Should Be Dynamic
* One input is the bucket name (enum, string, required).  This input should be an enum where the values are dynamically generated based on the buckets that can be written to given the AWS access key in the credentials.
* One input is the key name (string, required)
* One input is the Steward URL to upload (string, required)  **Note: It is not possible to access attachments from the component immediately prior to another component and attachment URLs can not be selected using the point and click link.  This is something that will be inconvienent at first but we will be able to over come it as the mapper is improved.**

## Behavior
[Some throwaway code that shows how to do this in JS](https://github.com/elasticio/Lloyds-s3-demo-component/blob/master/lib/actions/createS3Bucket.js)
Code should:
1. Read the data from the Steward URL.
2. Write the data to S3 using the bucket + key provided.  If the key already exists, allow AWS to overwrite the object.

## Output data
Emit an object where the body of the object contains all of the [Amazon headers in the resonse](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-responses)

## Gotchas
* [There are limits on the allowable chars in keys](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)  Perhaps we should throw an exception when we encounter a non-allowed key. 

## Not in scope (Limitations that can be done in future iterations)
* Setting Object Metadata in S3
* Support for objects that are so large, they can not fit in the memory of the component's docker container.
* Object more that 5 GB in size (so that they can always be uploaded in a single operation)
* Support for [Storage Classes](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html)
* Support for [Object Tagging](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html)
* Object compression (with zip, gzip, etc)
* Object encryption

**Comment by zubairov** [comment]
> One input is the Steward URL to upload (string, required) Note: It is not possible to access attachments from the component immediately prior to another component and attachment URLs can not be selected using the point and click link. This is something that will be inconvienent at first but we will be able to over come it as the mapper is improved.

This may never happen. Even if mapper could be potentially improved in the future attachments are not predictable nor formalized structure right now, therefore, we shouldn't rely on it now. This part needs additional thought.

> Support for objects that are so large, they can not fit in the memory of the component's docker container.

We should use [streaming here](https://github.com/apiaryio/s3-streaming-upload) here. This limitation shouldn't be imposed here.

**Comment by jhorbulyk** [comment]
> > Support for objects that are so large, they can not fit in the memory of the component's docker container.

>We should use streaming here here. This limitation shouldn't be imposed here.

If this is a hard requirement (i.e. must-have) for the first iteration, I can modify this (and other S3 issues) so that this idea is moved from the limitations section to the requirements section.  Should I go ahead and do that?

> > One input is the Steward URL to upload (string, required) Note: It is not possible to access attachments from the component immediately prior to another component and attachment URLs can not be selected using the point and click link. This is something that will be inconvienent at first but we will be able to over come it as the mapper is improved.

> This may never happen. Even if mapper could be potentially improved in the future attachments are not predictable nor formalized structure right now, therefore, we shouldn't rely on it now. This part needs additional thought.

One change that can be made using exclusively PS team resources is to start depricating the `msg.attachments` section of the message in favour of putting URLs to Steward attachments in the body.   However, that is a somewhat significant directional shift and I want commitment from PS management that we are clearly moving in this direction.
